www/todolist/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', "www.todolist.views.overview"),
    url(r'^overview/', "www.todolist.views.overview", name='overview'),
    url(r'^add/', "www.todolist.views.add", name='add'),
    url(r'^edit/(?P<todo_entry>\d+)/$',
        "www.todolist.views.edit", name='edit'),
    url(r'^delete/(?P<todo_entry>\d+)/$',
        "www.todolist.views.delete", name='delete'),
    url(r'^switch/(?P<todo_entry>\d+)/$',
        "www.todolist.views.switch", name='switch'),
    # Login/Logout
    url(r'^login/$', "django.contrib.auth.views.login", name="login"),
    url(r'^logout/$', views.logout_user, name="logout"),
]

www/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from todolist import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'www.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^todolist/', include('www.todolist.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^$', views.overview, name='overview'),
]

www/todolist/models.py
from django.db import models


class Todo_Entries(models.Model):
    creator = models.ForeignKey('auth.User')
    title = models.CharField(max_length=30)
    description = models.TextField(max_length=500)
    publication = models.DateTimeField(auto_now_add=True)
    duedate = models.DateField()
    duetime = models.TimeField(null=True)
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    PRIORITY_CHOICES = (
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
    )
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default=LOW)
    status = models.BooleanField("Open/Done", default=False)

www/todolist/views.py
from django.shortcuts import HttpResponse, get_object_or_404, redirect
from django.template.loader import get_template
from www.todolist.models import Todo_Entries
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.forms.models import ModelForm
from django import forms


class EntryForm(ModelForm):
    class Meta:
        model = Todo_Entries
        fields = ['title', 'description', 'duedate', 'duetime', 'priority']

    duetime = forms.TimeField(required=False)
    duedate = forms.DateField(error_messages={
        'required': 'Datum muss angegeben werden. (Zeit ist optional)'})


@login_required(login_url='django.contrib.auth.views.login')
def overview(request):
    t = get_template('overview.html')
    html = t.render({
        'done_entries': Todo_Entries.objects.filter(
            creator=request.user,
            status=True
            ),
        'open_entries': Todo_Entries.objects.filter(
            creator=request.user,
            status=False
            ),
        })
    return HttpResponse(html)


@login_required(login_url='django.contrib.auth.views.login')
def add(request):
    t = get_template('form.html')

    # Check if it's a POST or a GET-Request
    if request.method == 'POST':
        # For POST-Requests: fill a new form instance with data
        form = EntryForm(request.POST)
        if form.is_valid():
            entry = Todo_Entries()
            entry.title = form.cleaned_data['title']
            entry.description = form.cleaned_data['description']
            entry.duedate = form.cleaned_data['duedate']
            entry.duetime = form.cleaned_data['duetime']
            entry.priority = form.cleaned_data['priority']
            entry.creator = request.user
            entry.save()
            return redirect('overview')
    else:
        # For GET-Requests: create the blank form
        form = EntryForm()

    answer = RequestContext(request, {
        'form': form,
        })

    html = t.render(answer)
    return HttpResponse(html)


@login_required(login_url='django.contrib.auth.views.login')
def edit(request, todo_entry):
    t = get_template('form.html')
    entry = get_object_or_404(Todo_Entries, pk=todo_entry)

    # Check if it's a POST or a GET-Request
    if request.method == 'POST':
        # For POST-Requests: fill a new form instance with data
        form = EntryForm(request.POST)
        if form.is_valid():

            entry.title = form.cleaned_data['title']
            entry.description = form.cleaned_data['description']
            entry.duedate = form.cleaned_data['duedate']
            entry.duetime = form.cleaned_data['duetime']
            entry.priority = form.cleaned_data['priority']
            entry.save()
            return redirect('overview')
    else:
        # For GET-Requests: load entry
        form = EntryForm(instance=entry)

    answer = RequestContext(request, {
        'form': form,
        'todo_entry': todo_entry,
        })

    html = t.render(answer)
    return HttpResponse(html)


@login_required(login_url='django.contrib.auth.views.login')
def delete(request, todo_entry):
    entry = get_object_or_404(Todo_Entries, pk=todo_entry)
    entry.delete()

    return redirect('overview')


@login_required(login_url='django.contrib.auth.views.login')
def switch(request, todo_entry):
    entry = get_object_or_404(Todo_Entries, pk=todo_entry)
    entry.status = not entry.status
    entry.save()
    return redirect('overview')


@login_required(login_url='django.contrib.auth.views.login')
def logout_user(request):
    logout(request)
    return redirect('django.contrib.auth.views.login')

www/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>{% block sitetitle %}Todolist-Applikation{% endblock %}</title>
		<meta name="description" content="application to manage a list of todo-entries">
		<meta name="author" content="Stefan Wimmer and Bernhard Widmann">
	</head>
	<body>
		<header>
			<h1><a href="{% url 'overview' %}">TO-DO</a></h1>
			<nav>{% block header %}{% endblock %}</nav>
		</header>
		<div id="content">
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

www/templates/form.html
{% extends "base.html" %}

{% block sitetitle %}
	{% if todo_entry %}Ändern{% else %}Hinzufügen{% endif %}
{% endblock %}

{% block header %}
<ul>
	<li><a href="{% url 'overview' %}" class="overview">Übersicht</a></li>
</ul>
{% endblock %}

{% block content %}
<section class="form">
	{% if todo_entry %}
	<form action="{% url 'edit' todo_entry %}" method='post'>
		<h2>Ändern</h2>
	{% else %}
	<form action="{% url 'add' %}" method='post'>
		<h2>Hinzufügen</h2>
	{% endif %}
		{% csrf_token %}
		{% for field in form %}
			{{ field.label_tag }}
			{{ field }}
			{{ field.errors }}<br>
		{% endfor %}
		<nav>
			<ul>
				<li><input type="submit" value="Abschicken" class="submit"/></li>
				<li><a href="{% url 'overview' %}" class="overview">Abbrechen</a></li>
				{% if todo_entry %}
					<li><a href="{% url 'delete' todo_entry %}" class="delete">Löschen</a></li>
				{% endif %}
			</ul>
		</nav>
	</form>
</section>
{% endblock %}

www/templates/form_old.html
<!DOCTYPE html>
<html>
<head lang = "en">
<meta charset="UTF-8">
<title>Todo-Entry</title>
</head>
<body>

{% if todo_entry %}
<form action="{% url 'edit' todo_entry %}" method='post'>
{% else %}
<form action="{% url 'add' %}" method='post'>
{% endif %}

{% csrf_token %}

{% for field in form %}
	{{ field.label_tag }}
	{{ field }}
	{{ field.errors }}<br>
{% endfor %}

<input type="submit" value="Submit" />

{% if todo_entry %}
&nbsp;&#124;&nbsp;<a href="{% url 'delete' todo_entry %}">Delete</a>
{% endif %}

</form>
</body>
</html>

www/templates/form_v2.html
{% extends "base.html" %}

{% block sitetitle %}
	{% if todo_entry %}Ändern{% else %}Hinzufügen{% endif %}
{% endblock %}

{% block header %}
<ul>
	<li><a href="{% url 'overview' %}" class="overview">Übersicht</a></li>
</ul>
{% endblock %}

{% block content %}
{% if todo_entry %}
<section class="edit">
	<form action="{% url 'edit' todo_entry %}" method='post'>
		{% csrf_token %}
		<h2>Ändern</h2>
		{% for field in form %}
			{{ field.label_tag }}
			{{ field }}
			{{ field.errors }}<br>
		{% endfor %}
		<nav>
			<ul>
				<li><input type="submit" value="Abschicken" class="submit"/></li>
				<li><a href="{% url 'overview' %}" class="overview">Abbrechen</a></li>
				<li><a href="{% url 'delete' todo_entry %}" class="delete">Löschen</a></li>
			</ul>
		</nav>
	</form>
</section>


{% else %}
<section class="add">
	<form action="{% url 'add' %}" method='post'>
		{% csrf_token %}
		<h2>Hinzufügen</h2>
		{% for field in form %}
			{{ field.label_tag }}
			{{ field }}
			{{ field.errors }}<br>
		{% endfor %}
		<nav>
			<ul>
				<li><input type="submit" value="Abschicken" class="submit"/></li>
				<li><a href="{% url 'overview' %}" class="overview">Abbrechen</a></li>
			</ul>
		</nav>
	</form>
</section>
{% endif %}
{% endblock %}

www/templates/overview.html
{% extends "base.html" %}

{% block sitetitle %}Übersicht{% endblock %}

{% block header %}
<ul>
	<li><a href="{% url 'add' %}" class="add">Neuer Eintrag</a></li>
	<li><a href="{% url 'logout' %}" class="logout">Ausloggen</a></li>
</ul>
{% endblock %}

{% block content %}
<section id="open">
	<header>
		<h2>Offen</h2>
	</header>
	{% for entry in open_entries %}
		<article>
			<h3>{{ entry.title }}</h3>
			<p class="subtitle">
				zu erledigen bis  
				{% if entry.duedate %}
					<time datetime="{{ entry.duedate }}">{{ entry.duedate|date:"d. F. Y" }}, </time>
				{% else %}
					irgendwann
				{% endif %} 
				{% if entry.duetime %}
					<time datetime="{{ entry.duetime }}">{{ entry.duetime|time:"H:i" }} Uhr</time>
				{% else %}
					irgendwann
				{% endif %}
			</p>
			<p class="priority">Priorität: {{ entry.get_priority_display }}</p>
			<p class="description">Beschreibung: {{ entry.description }}</p>
			<nav>
				<ul>
					<li><a href="{% url 'edit' entry.id %}" class="edit">Ändern</a></li>
					<li><a href="{% url 'switch' entry.id %}" class="switch">Statuswechsel</a></li>
				</ul>
			</nav>
		</article>
	{% endfor %}
</section>
<section id="done">
	<header>
		<h2>Erledigt</h2>
	</header>
	{% for entry in done_entries %}
		<article>
			<h3>{{ entry.title }}</h3>
			<p class="subtitle">
				zu erledigen bis 
				{% if entry.duedate %}
					<time datetime="{{ entry.duedate }}">{{ entry.duedate|date:"d. F. Y" }}, </time>
				{% else %}
					irgendwann
				{% endif %}
				{% if entry.duetime %}
					<time datetime="{{ entry.duetime }}">{{ entry.duetime|time:"H:i" }} Uhr</time>
				{% else %}
					irgendwann
				{% endif %}
			</p>
			<p class="priority">Priorität: {{ entry.get_priority_display }}</p>
			<p class="description">Beschreibung: {{ entry.description }}</p>
			<nav>
				<ul>
					<li><a href="{% url 'edit' entry.id %}" class="edit">Ändern</a></li>
					<li><a href="{% url 'switch' entry.id %}" class="switch">Statuswechsel</a></li>
				</ul>
			</nav>
		</article>
	{% endfor %}
</section>
{% endblock %}

www/templates/overview_old.html
<!DOCTYPE html>
<html>
<head lang = "en">
<meta charset="UTF-8">
<title></title>
</head>
<body>

<h1 align="center">Todolist-Overview</h1>
<br>

<h2>Offen</h2>
<h4>Title | Date and Time of Publication</h4>
<hr />

{% for entry in open_entries %}
	{{ entry.title }}&nbsp;&#124;&nbsp;
	{{ entry.publication }}&nbsp;&#124;&nbsp;
	<a href="{% url 'edit' entry.id %}">edit</a>&nbsp;&#124;&nbsp;
	<a href="{% url 'switch' entry.id %}">switch</a>&nbsp;&#124;&nbsp;
	<a href="{% url 'delete' entry.id %}">delete</a>
	<br />
{% endfor %}
<br />

<h2>Erledigt</h2>
<h4>Title | Date and Time of Publication</h4>
<hr />

{% for entry in done_entries %}
	{{ entry.title }}&nbsp;&#124;&nbsp;
	{{ entry.publication }}&nbsp;&#124;&nbsp;
	<a href="{% url 'edit' entry.id %}">edit</a>&nbsp;&#124;&nbsp;
	<a href="{% url 'switch' entry.id %}">switch</a>&nbsp;&#124;&nbsp;
	<a href="{% url 'delete' entry.id %}">delete</a>
	<br />
{% endfor %}
<br />

<hr />
<a href="{% url 'add' %}">add</a>
<a href="{% url 'logout' %}">logout</a>

</body>
</html>